name: lyqx
description: "An ecommerce assessment project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4

  # State Management (BLoC Pattern)
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  injectable: ^2.4.4
  get_it: ^8.0.2

  # API Calls & HTTP
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^14.6.2

  # Local Storage
  shared_preferences: ^2.3.3

  # Image Loading & Caching
  cached_network_image: ^3.4.1

  # Utilities
  dartz: ^0.10.1  # For functional programming (Either type)
  logger: ^2.4.0  # For better logging
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_light.png
  color_dark: "#121212"
  image_dark: assets/hometender_darkmode.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  # Add assets folder for images/icons
  assets:
    - assets/
    - assets/images/